### ISSUE TITLE
HI everyone 

### ISSUE THREAD

**Issue by dansaybolton** [sismo-core/sismo-protocol#60]
How are you all doing? The project Is really great. Haven't found any flaws since. Will contact you when I do.

**Comment by Kosteskot** [comment]
The project Is really great

**Comment by WolfDiablo** [comment]
норм проект

**Comment by Evdokim12** [comment]
hi

**Comment by kaskara12** [comment]
Hallo! It's a great project!

**Comment by WolfDiablo** [comment]
как живете

**Comment by 8bit0x01** [comment]
Hello everybody 😀
